#! /usr/bin/env python3

# Using /nese/toltec/dataprod_lmtslr/data_lmt/data_lmt.log
# 2022S1SEQUOIACommissioning - Science
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2022S1SEQUOIACommissioning"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["R-Cas"] = \
 [ 94050, 94051, 94052,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["R-Cas"] = ""

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["R-Cas"] = "pix_list=-5,8,12,13"

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["R-Cas"] = ""

# Found 1 source(s) for 2022S1SEQUOIACommissioning

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
